version: "3.8"

services:
  userdb:
    image: postgres:16
    container_name: medcenter-userdb
    environment:
      POSTGRES_DB: medicalcenter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sjsjsqo18ha5
    ports:
      - "5433:5432"
    volumes:
      - userdb-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d medicalcenter" ]
      interval: 10s
      timeout: 5s
      retries: 10

  authdb:
    image: postgres:16
    container_name: medcenter-authdb
    environment:
      POSTGRES_DB: authservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sjsjsqo18ha5
    ports:
      - "5435:5432"
    volumes:
      - authdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  authdb-data:
  userdb-data: