spring.application.name=AuthService
server.port=8080
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5435/authservice
spring.datasource.username=postgres
spring.datasource.password=sjsjsqo18ha5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=b6fb094d7d037d35f459507c0db490c2a1a01dad31a460cd799c7cf0579d770a
security.jwt.access-expiration-time=900000
security.jwt.refresh-expiration-time=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tp.medicalservice@gmail.com
spring.mail.password=zvti wkto zkhh uhtx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.debug=true

logging.file.name=logs/authservice/authservice.log
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10KB
logging.level.medicalcenter.authservice=DEBUG
logging.level.org.springdoc=INFO

spring.config.import=optional:file:.env[.properties]