spring.application.name=AuthService
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5435/authservice
spring.datasource.username=postgres
spring.datasource.password=sjsjsqo18ha5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=b6fb094d7d037d35f459507c0db490c2a1a01dad31a460cd799c7cf0579d770a
security.jwt.access-expiration-time=900000
security.jwt.refresh-expiration-time=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tp.medicalservice@gmail.com
spring.mail.password=zvti wkto zkhh uhtx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:file:.env[.properties]