spring.application.name=AuthService
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5435/authservice
spring.datasource.username=postgres
spring.datasource.password=sjsjsqo18ha5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect